name: attempts

on: push

jobs:
  
  greeting_workflow:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Echo word
        run: echo "ABCD"
      
      - name: Installing google-cloud-storage
        run: pip install google-cloud-storage
      
      - name: Printing secret
        run: printf ${{secrets.AUTH_JSON_FILE}} | sed 's/ ./& /g'
      
      - name: Making files
        run: echo ${{secrets.AUTH_JSON_FILE}} > tmp/auth_file.json
        
      - name: Setting environment variable
        run: export GOOGLE_APPLICATION_CREDENTIALS="tmp/auth_file.json"
      
      - name: Running Python file
        run: python3 File_Uploader.py
